const EVENTS = {
  CONNECT: "connection",
  DISCONNECT: "disconnect",

  CREATE_ROOM: "CREATE_ROOM",
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  SET_NAME: "SET_NAME",
  UPDATE_COSMETICS: "UPDATE_COSMETICS",
  READY_TOGGLE: "READY_TOGGLE",
  START_MATCH: "START_MATCH",
  PLAYER_ACTION: "PLAYER_ACTION",
  PAUSE_GAME: "PAUSE_GAME",
  RESUME_GAME: "RESUME_GAME",
  QUIT_GAME: "QUIT_GAME",
  REQUEST_REMATCH: "REQUEST_REMATCH",
  START_SINGLE_PLAYER: "START_SINGLE_PLAYER",
  UPDATE_SETTINGS: "UPDATE_SETTINGS",

  ROOM_CREATED: "ROOM_CREATED",
  ROOM_JOINED: "ROOM_JOINED",
  ROOM_STATE: "ROOM_STATE",
  PLAYER_JOINED: "PLAYER_JOINED",
  PLAYER_LEFT: "PLAYER_LEFT",
  MATCH_STARTED: "MATCH_STARTED",
  ROUND_COUNTDOWN: "ROUND_COUNTDOWN",
  ROUND_SIGNAL: "ROUND_SIGNAL",
  ROUND_RESULT: "ROUND_RESULT",
  SCORE_UPDATE: "SCORE_UPDATE",
  GAME_PAUSED: "GAME_PAUSED",
  GAME_RESUMED: "GAME_RESUMED",
  GAME_QUIT: "GAME_QUIT",
  MATCH_FINISHED: "MATCH_FINISHED",
  SYSTEM_MESSAGE: "SYSTEM_MESSAGE",
  ERROR_MESSAGE: "ERROR_MESSAGE",
};

const GAME = {
  MIN_PLAYERS: 2,
  MAX_PLAYERS: 4,
  DEFAULT_DURATION_MS: 90000,
  COUNTDOWN_MS: 3000,
  SUSPENSE_MIN_MS: 600,
  SUSPENSE_MAX_MS: 1400,
  RESPONSE_MIN_MS: 900,
  RESPONSE_MAX_MS: 1200,
  BETWEEN_ROUND_MS: 600,
  SIGNALS: ["ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight"],
};

const COSMETIC_OPTIONS = {
  hatColor: ["red", "white", "black"],
  footwear: ["boots", "sneakers", "slippers"],
  badge: ["lightning", "coffee", "bug", "none"],
  codingAffinity: ["casual", "dedicated", "unhealthy"],
};

const KEY_ALIASES = {
  KeyW: "ArrowUp",
  KeyS: "ArrowDown",
  KeyA: "ArrowLeft",
  KeyD: "ArrowRight",
};

module.exports = {
  EVENTS,
  GAME,
  COSMETIC_OPTIONS,
  KEY_ALIASES,
};
